### ISSUE TITLE
syntax error / module not found

### ISSUE THREAD

**Issue by PeterPusztai** [cbdelavenne/fb-messenger-media-scraper#7]
Hi!
I tried to run your script, following the execution guide.
If I run with "python ./fbm-scraper.py", I get the error:  

 File "./fbm-scraper.py", line 162
    print('+', sep=' ', end='', flush=True)
                  ^
SyntaxError: invalid syntax

If I run it with "python3 ./fbm-scraper.py", I get the error:

Traceback (most recent call last):
  File "./fbm-scraper.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Any idea what have I done wrongly? Thanks!

**Comment by cbdelavenne** [comment]
Hey @PeterPusztai 

Did you install the prerequisites as instrucuted in the `README.md` ?

```
pip install -r requirements.txt
```
